name: Build QM from TXT

on:
  push:
    paths:
      - 'translations/*.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y qttools5-dev-tools python3 python3-pip

      - name: Convert TXT to TS
        run: python3 convert_txt_to_ts.py translations/myfile.txt output.ts --lang zh_CN

      - name: Compile TS to QM
        run: lrelease output.ts -qm output.qm

      - name: Upload QM artifact
        uses: actions/upload-artifact@v4
        with:
          name: qm-file
          path: output.qm
