name: Build QM from TXT  # 工作流名字

on:
  push:
    paths:
      - 'translations/*.txt'  # 只要上传 TXT 就触发
  workflow_dispatch:         # 也可以手动触发

jobs:
  build:
    runs-on: ubuntu-latest   # 使用 Ubuntu 服务器跑

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 拉取仓库内容

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y qttools5-dev-tools python3 python3-pip
        # 安装 Qt 工具（lrelease）和 Python

      - name: Convert TXT to TS
        run: python3 convert_txt_to_ts.py translations/myfile.txt output.ts --lang zh_CN
        # 运行 Python 脚本把 TXT 转 TS

      - name: Compile TS to QM
        run: lrelease output.ts -qm output.qm
        # 用 lrelease 编译生成 QM 文件

      - name: Upload QM artifact
        uses: actions/upload-artifact@v3
        with:
          name: qm-file
          path: output.qm
          # 上传 QM 文件作为产物，可以下载
